### ISSUE TITLE
Update Model-service to align with new AMR model schema

### ISSUE THREAD

**Issue by dvince2** [DARPA-ASKEM/Terarium#1129]
FYI: there's been little progress with a new AMR so I can't imagine this will be started let alone completed (by me at least @tangopapatime) before I start my Vacation next week.

### TODO list, roughly in sequence
- [x] Copy model schemas from https://github.com/DARPA-ASKEM/Model-Representations
- [x] Create converter to go from AMR-Petri to IGraph for rendering/editing
- [x] Update to petrinet-renderer (AMR -> Graph)
- [ ] Update model-page to use new schema
  - [ ] Model page update
  - [ ] Discussion on parameter vs config as first-class citizens in TDS when creating new config/parameters
- [ ] Second round of updating and refinement of schemas from https://github.com/DARPA-ASKEM/Model-Representations, because some things are likely to change...
- [ ] Update to data explorer
  - [ ] Breaking changes to facets
  - [ ] Breaking changes to search
  - [ ] Breaking changes to search items 
- [ ] HMI Server cleanup, remove unneeded entities and classes
- [ ] HMI Client cleanup, typing and things

### TODO list, can do in parallel
- [ ] TA1 Equation API changes
- [ ] TA1 model extraction API changes
- [ ] TA2 Stratification changes. in model-service
  - [ ] Check stratification can take in new model format
  - [ ] Check the result of stratification can be converted back into new format
- [ ] TA3 Simulation service API changes
  - [ ] Check new model format is supported
  - [ ] Check if we can reset ENABLE_TDS flag back to true
