### ISSUE TITLE
[TASK]: Second pass at 'Search by Example'

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#1220]
**Describe the task**
The 'Search by Example' feature is incomplete. Now that we have more control with access to ES, let's do a second pass to remove some rough edges.

**Task Items**
- [x] Update the search bar to reflect which search was issued e.g. Similar content to: [name of resource]
- [x] Update the 'Showing...' message to reflect which search was issued. e.g. Showing xxx results for similar content to: [name of resources]
- [ ] Get bigger set of results and populate the facets like any other search

**Current state**
- search context is from previous search, not the search by example one
- no facets
- only 10 results
<img width="1792" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/1a84544b-b595-41e5-9a39-ef58fa0ed9ae">
