### ISSUE TITLE
[TASK]: "Search by Example" - get bigger set of results and populate the facets like any other search

### ISSUE THREAD

**Issue by Jami159** [DARPA-ASKEM/Terarium#1366]
Describe the task
The 'Search by Example' feature is incomplete. Now that we have more control with access to ES, let's do a second pass to remove some rough edges.

@iross has given us this sample URL: https://xdddev.chtc.io/api/v2/articles?docid=5e7e0724998e17af8269b284&similar_docs=true

Swagger docs: https://xdd.wisc.edu/api-docs/

**Task Items**
- [ ] In `application.properties` you can find the name of the xDD developer instance.  Change `DocumentProxy.java` to use this developer instance instead of the production resource.
- [ ] In `DocumentResource.java`, add a new `@QueryParam` to the `getDocuments` method for the new `similar_docs` query parameter. You will also need to modify the interface `DocumentProxy.java`
- [ ] In `getDocuments` add a bit of safety code that requires a docid to be set (and not a term, doi or github_url). Consider returning an error if the search does contain those.

If you click on the link above, you'll see the raw JSON returned. Inside of `success>data>0` is a document object which in our back end is represented by `Document.java`. 

- [ ] Create a new java class called SimilarDocuments.java in the same directory as Document.java.
- [ ] Add two fields to this list - one should be a list of `Document`s annotated with `@JsonAlias(bibjsons)`, and the other should be a map of facets like `private Map<String, XDDFacetsItemResponse> facets;`
- [ ] Now on `Document.java` add a simlarDocument field (annotated with `@JsonAlias(simlar_docs)`).
- [ ] Now, modify our front end to not make a call to the related documents end point, but instead, it should call into the getDocuments endpoint.

Then... hook up facets :)

**Current State**
- only 10 results

**Note**
This is a follow up task from task #1220
