### ISSUE TITLE
[TASK]: Set configurations value

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/Terarium#1413]
**Describe the task**
We need to be able to change and save configurations value

Value are in `configurations.semantics.ode.parameters`, and will be saved there.

**Task Items**
- [x] Display `name` and `value` on the modal page
- [x] If the parameters also has a `distribution`, display the min/max and the _distribution_
- [x] Let the user save `name` and `value` and  distribution `minimum` and `maximum`  if selected via a checkbox _distribution_
 ```
           {
              "id": "beta",
              "name": "beta",
              "description": "infection rate",
              "value": 0.027,
              "distribution": {
                "type": "Uniform1",
                "parameters": {
                  "minimum": 0.026,
                  "maximum": 0.028
                }
              }
            },
```
- [x] Save configuration to the back end.
`import {	updateModelConfiguration } from '@/services/model-configurations';`
