### ISSUE TITLE
[TASK]: Clean dependencies 

### ISSUE THREAD

**Issue by dvince2** [DARPA-ASKEM/Terarium#1704]
**Describe the task**
Some cleanup can be done on dependencies.

**Task Items**
- [x] elasticsearch is not being used. remove it from build.gradle
- [x] org.glassflish.jersey is not being used. remove it
- [x] Remove remaining usages of AWS SDK for S3 upload in favour of presigned URLs.
- [x] Remove AWS as dependency
- [x] Remove AWS secrets from terarium project and local dev's hmi-server secrets
- [x] While there, fix the "double colon" issue on keycloak's secret which was reverted from the quarkus 3.0 branch

**Goal**
General project cleanup should be done from time to time.
