### ISSUE TITLE
[TASK]: Operator header

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2191]
**Describe the task**
We need to update the header of all operators to be common.
- Figma link: https://www.figma.com/file/yCstHNeLLPx0TzZC9uWXbl/Terarium---November-2023?node-id=835%3A439850&mode=dev
- Screenshot: 
<img width="415" alt="Screenshot 2023-11-09 at 9 48 20 AM" src="https://github.com/DARPA-ASKEM/terarium/assets/28237258/0bc1156b-4d76-494e-b75d-46dd96526ccb">

**Task Items**
- [x] Create a new component called `tera-operator-header`
- [x] Header contains only one line of copy, needs to truncate into an ellipsis if too long (less than 1rem of three dots button)
    - [x] The copy should be a prop.
- [x] Background should be light green; see figma for colour, and use/create CSS variable for it.
    - [x] the background colour should respond to CSS variables based on a `status` prop. _Not used yet_
    - [x] Those status should be an enum define in a `operator.ts` util.
        - [x] Default
        - [x] Hover/Drag
        - [x] Loading
        - [x] Success
        - [x] UserError
        - [x] Process Fail
        - [x] Disabled
- [x] Update three dots button to contains a menu component
    - [x] Remove
    - [x] Duplicate (disabled)
    - [x] Bring to front (disabled)
    - [x] Send to back (disabled)
    - [x] Open in New Window _open the drilldown in a new window (remove lightning bolt)_

Figma link: https://www.figma.com/file/yCstHNeLLPx0TzZC9uWXbl/Terarium---November-2023?type=design&node-id=995-127423&mode=design&t=18eWIaRUcbF8HMHu-0

![Screenshot 2023-11-10 at 8 20 48 AM](https://github.com/DARPA-ASKEM/terarium/assets/636801/0417cf63-f5b7-4d8c-bc45-d7a372fb4e3e)
