### ISSUE TITLE
[TASK]: Operator inputs

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2192]
**Task Items**

- [x] Operator inputs must be its own component `tera-operator-inputs`
- [x] if inputs prop empty, do not display
- [x] by default an input needs to be `secondary` styling, but `primary` when plugged in.
- [x] if an input as a flag set to optional, display the copy `(optional)` after it.
- [x] if input is plugged in, hover should offer the user to _unlink_ by clicking on it. Display a `unlink` copy or a broken chain icon.

![image](https://github.com/DARPA-ASKEM/terarium/assets/28237258/69d26393-2b48-4aea-a987-c8e669c60c40)

Figma link: https://www.figma.com/file/yCstHNeLLPx0TzZC9uWXbl/Terarium---November-2023?type=design&node-id=995-127423&mode=design&t=18eWIaRUcbF8HMHu-0

![Screenshot 2023-11-10 at 8 20 48 AM](https://github.com/DARPA-ASKEM/terarium/assets/636801/0417cf63-f5b7-4d8c-bc45-d7a372fb4e3e)
