### ISSUE TITLE
[TASK]: Operator action button

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2194]
**Describe the task**
Need to create a new component to configure action buttons on the operator.

**Task Items**
- [x] Create a new component called `tera-operator-action`
- [x] A prop array will provide a list of actions `TeraOperatorAction` type, to select how to label them and if they are primary or not
```typescript
[ 
    { "label": "Review sanity checks", "action": "review", "primary": false, "icon": false },
    { "label": "Run", "action": "run", "primary": true, "icon": false },
]
```
- [x] the icon field is for the operator to specify an icon to the left of the button (see chat button)
- [x] Clicking on the button will call an emit `action` that send the value from the `action` field back to the operator.

**Goal**
A clear and concise description of what the end result must have for it to be approved as complete.

**Screenshots**
<img width="594" alt="Screenshot 2023-11-09 at 10 12 39 AM" src="https://github.com/DARPA-ASKEM/terarium/assets/636801/e9effef1-24c7-4f00-9ec4-0f0f34f0b580">
<img width="1099" alt="Screenshot 2023-11-09 at 10 12 48 AM" src="https://github.com/DARPA-ASKEM/terarium/assets/636801/b7cf45d4-9333-4cc0-ba03-550b37ce038d">

Figma link: https://www.figma.com/file/yCstHNeLLPx0TzZC9uWXbl/Terarium---November-2023?type=design&node-id=995-127423&mode=design&t=18eWIaRUcbF8HMHu-0

![Screenshot 2023-11-10 at 8 20 48 AM](https://github.com/DARPA-ASKEM/terarium/assets/636801/0417cf63-f5b7-4d8c-bc45-d7a372fb4e3e)
