### ISSUE TITLE
[TASK]: Operator image caroussel

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2311]
**Describe the task**
Operators can display one or more images of the operations.

**Task Items**
- [x] Create a box with the appropriate radius and borders.
- [x] Display a simple image icon if no image has been provided.
- [x] Center the image vertically and horizontally within the box.
- [x] A grey background is to be applied if the image does not fit the whole box.
- [x] Display a button list selector to display which image is currently visible. Make the click area of those buttons as big as possible.

**Screenshots**
<img width="795" alt="Screenshot 2023-11-25 at 13 41 35" src="https://github.com/DARPA-ASKEM/terarium/assets/636801/57496b58-b956-4fcb-8589-f5547b84dd64">
![image](https://github.com/DARPA-ASKEM/terarium/assets/141876103/dca471a2-814d-401e-9083-35e8118a4512)

**Additional context**
[Figma link](https://www.figma.com/file/yCstHNeLLPx0TzZC9uWXbl/Terarium---November-2023?node-id=1014%3A191893&mode=dev)
