### ISSUE TITLE
[TASK]: Operator SVG preview

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2312]
**Describe the task**
Create a simple component to display those 9 SVGs (more possible in the future) selected by a simple prop enum.

**Task Items**
- [x] Hard code the SVGs in the component, or download them as SVGs or png
- [x] Create an enum for each use case
- [x] have a default value in case there is no prop or value

**Screenshots**
<img width="607" alt="Screenshot 2023-11-25 at 14 12 59" src="https://github.com/DARPA-ASKEM/terarium/assets/636801/6755e1aa-38f1-4313-bd99-6f00f6de8874">

**Additional context**
[Figma link](https://www.figma.com/file/yCstHNeLLPx0TzZC9uWXbl/Terarium---November-2023?node-id=1014%3A192641&mode=dev)
