### ISSUE TITLE
[TASK]: Use new ProjectAssets and remove duplicate Project and Workflow model impl. on front end

### ISSUE THREAD

**Issue by dvince2** [DARPA-ASKEM/terarium#2476]
**Describe the task**
Currently, in `Project.ts` we have a second implementation of the Project model.  This duplicate project contains a field `assets` which contains all of the project's actual assets (documents, models, workflows, etc etc) in addition to the standard Project fields.  This is a holdover from using TDS, and is not idea because we don't need to have all of these assets held in memory.  In the new Project model as defined in `Types.ts` there is a `projectAssets` field which contains the metadata about an asset but not the asset itself.  This is what should be used, then just when needed, we can ask the back end for the actual asset to display to the user.
When the correct calls have been made we will also run into an issue with Workflows, as workflows have been entirely defined in the front end with the back end models being dummy objects.  I've updated our back end to have the correct typing but the front end will need to be changed to use the workflow objects from Types.ts

**Tasks to do**
- [ ] Remove the IProject model in favour of the Project model
- [ ] Get rid of the call to `/projects/${projectId}/assets` in `services/project.ts`
- [ ] Replace lightweight front end display of assets to use `Project.projectAssets`
- [ ] Replace manipulation of actual assets with a call to the correct back end controller to get the actual Dataset/Model/Workflow
- [ ] Replace workflows and their related objects with the new types.ts models.
