### ISSUE TITLE
[TASK]: Model Config UI improvements

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/terarium#2591]
**Describe the task**
Now that we've got some good functionality around the model config drilldown, lets address some UI feedback on the model config

**Task Items**
- [ ] Change title case labels to sentence case
- [ ] Add some uniformity to minimum column widths (see example)
- [x] Drop downs in a column should have the same width
- [ ] Can we add keyword filter and column visibility controls to the tables?
- [x] Page footer - can we add a semi-opaque fill with a slight blur effect so that we can see additional scrollable table content? (see example)
- [ ] Add the word “Matrix” next to the matrix icons in the Value type column
- [ ] Add a short description about the matrix, such as the size (e.g. “4 x 2 matrix”)
- [x] Shorten field validation error messages to one line
- [ ] Increase the height of rows that need to accommodate a validation error to avoid the field jumping around vertically each time there is an error and the message is displayed.
- [ ] Focussed field outline should change from green to red on error.
- [ ] Set the background colour of the table’s header row to #EFF1F2
- [ ] When a row is expanded, set the parent row background colour to #E5EFE5 and the background colour of the child rows to #F2F7F1
- [x] Move the Run button to the right side, to the left of Close
- [x] Make the `Source` field an editable string

**Screenshots**

![Image](https://github.com/DARPA-ASKEM/terarium/assets/33158416/e5fff918-ac39-4143-978c-ff1c7f162189)
![Image](https://github.com/DARPA-ASKEM/terarium/assets/33158416/55b4f7a2-844e-4688-9339-6ab4712fcca0)
![Image](https://github.com/DARPA-ASKEM/terarium/assets/33158416/88f40651-4b94-4a65-a317-d98784a437eb)

![Image](https://github.com/DARPA-ASKEM/terarium/assets/636801/62207e95-9a57-4b05-8488-cda663fb133a)
