### ISSUE TITLE
[TASK]: Improve Notebook view of Dataset transformer operator

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2598]
**Describe the task**
There are new design available to improve how beaker needs to be displayed on the Notebook view of an operator.
This task is to start creating the main component to implement those design choices and apply them to one operator (Dataset transformer) before applying to others.

**Task Items**
- [x] Design team will update the UI
- [ ] Create a dual section with a preview
- [ ] The results of a code run is to be visualize in the preview panel
- [ ] Render error messages within the preview panel
- [ ] The chat box needs to be fixed on top left panel
- [ ] A language selector (Python/Julia) needs to be available, some operator will not be able to switch it's value
- [ ] If the user edit the code it needs to be sent to beaker as part of the new context
- [ ] the user will have the ability to 'Ask' a question to Beaker LLM to get some code, that can be executed with the `Run` button, but also a 'Ask and Run' button that will do both and therefore avoid a back and forth with beaker to get results.

**Comment by jamiewaese-uncharted** [comment]
FIGMA LINK
https://www.figma.com/file/w4BmFSXhtXTqQy3T7cpWy3/Terarium---January-2024?type=design&node-id=1297%3A68614&mode=design&t=mokC7NTx6OzuCXnh-1

PROTOTYPE
[https://www.figma.com/proto/w4BmFSXhtXTqQy3T7cpWy3/Terarium---January-2024?page-id=[…]aling=min-zoom&starting-point-node-id=1315%3A61165&mode=design](https://www.figma.com/proto/w4BmFSXhtXTqQy3T7cpWy3/Terarium---January-2024?page-id=1297%3A68614&type=design&node-id=1315-61165&viewport=334%2C973%2C0.13&t=Q9tKaXdVyyuEa6ri-1&scaling=min-zoom&starting-point-node-id=1315%3A61165&mode=design)

VIDEO
https://github.com/DARPA-ASKEM/terarium/assets/120480244/7ac8ef41-5691-45e5-a40f-ee1562155e3b

PICTURES
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/4332987b-91d5-4b2f-ab0a-882e090f92ad)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/d7bbb176-8a6b-42b4-834c-666b464ade6a)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/07485d1b-0102-455b-8207-f740b449ac06)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/2855acc4-4b8c-4f94-ac3b-4d31f0218047)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/1dd3c76a-c9c2-4fbf-af60-c7541000d660)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/26305a3f-1a99-4b86-9f53-04bcd2f6fb93)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/739ba35a-290a-4f32-b91c-466f36e707b5)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/879bd30b-04d7-4faf-95c6-a2ce05fa45c1)

**Comment by dgauldie** [comment]
Try to do this issue in the second week of the spring
