### ISSUE TITLE
[TASK]: Add an `isTemporary` flag to all assets

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2599]
**Describe the task**

A temporary asset is an asset that needs to exist in the data-service for processing task within operators in the workflow.
But they should never appears in search, nor in project. They are only visible in the hmi-client to the operator that manipulate them.
We need a simple way to define them.

**Task Items**
- [x] add a way for the `hmi-client` to create _temporary_ assets
- [x] those _temporary_ assets should not be searchable, nor visible within a `Project.projectAssets[]`
- [x] a _temporary_ asset can become a normal asset easily
- [x] a _normal_ asset cannot become a _temporary_ asset
- [x] Needs to be available on all assets except _Project_
