### ISSUE TITLE
[TASK]: Add support for Decapodes in HMI

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2632]
**Describe the task**
`Model.java` model needs to be updated to support the _Decapodes AMR_ [schema](https://github.com/DARPA-ASKEM/Model-Representations/tree/main/decapodes).

**Task Items**
- [ ] Find the differences between the _Petrinet AMR_ and _Decapodes AMR_
- [ ] Implement a solution to support both AMR' schemas
- [ ] Create controllers to allow services to access either
- [ ] Write test
