### ISSUE TITLE
[TASK]: Support Decapodes AMR

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2638]
**Describe the task**

We need to support _Decapodes_ [AMR](https://github.com/DARPA-ASKEM/Model-Representations/blob/main/decapodes/json/amr_schema.json) in the data-service.

**Task Items**
- [ ] Create new model `DecapodesContext.java` 
```Java
// Just be a wrapper around a JSON blob.
private ModelHeader header;
private Object context;
@JsonProperty("parent_model")
private UUID modelId;
```
- [ ] Create new model `DecapodesConfiguration.java`
```Java
// Just be a wrapper around a JSON blob.
private ModelHeader header;
private Object configuration;
@JsonProperty("parent_context")
private UUID decapodesContextId;
```
- [ ] `/api/models/decapodes` endpoint to generate a _Decapodes_ AMR **Model**
[example of a JSON output](https://github.com/DARPA-ASKEM/Model-Representations/blob/main/decapodes/examples/grigoriev/model.json)
```JS
{
   "header": { 
      "id": UUID,
      // ...all properties of 'header'
    },
   "model": // ...all properties of 'model'
}
```

- [ ] `/api/model-contexts/decapodes/{id}` endpoint to generate a _Decapodes_ AMR **Context**
[example of a JSON output](https://github.com/DARPA-ASKEM/Model-Representations/blob/main/decapodes/examples/grigoriev/context.json)
```JS
{
   "header": { 
      "id": UUID,
      "parent_model": UUID,
      // ...all properties of 'header'
    },
   "context": // ...all properties of 'context'
}
```

- [ ] `/api/model-contexts/decapodes/{id}` endpoint to generate a _Decapodes_ AMR **Configuration**
[example of a JSON output](https://github.com/DARPA-ASKEM/Model-Representations/blob/main/decapodes/examples/grigoriev/configuration.json)
```JS
{
   "header": { 
      "id": UUID,
      "parent_context": UUID,
      // ...all properties of 'header'
    },
   "configuration": // ...all properties of 'configuration'
}
```

- [ ] `/api/model-combined/decapodes/{DecapodesConfigurationId}` endpoint to generate a _Decapodes_ AMR **Combined** 
[example of a JSON output](https://github.com/DARPA-ASKEM/Model-Representations/blob/main/decapodes/examples/grigoriev/combined.json)
This one needs to combine a Model, DecapodesContext, and DecapodesConfiguration in one result.
The DecapodesContext is fetch via `parent_context` in DecapodesConfiguration.
The Model is fetch via `parent_model` in DecapodesContext.
```JS
{
   "header": { 
      "id": UUID, // Id of the Model
      // ...all properties of 'header'
    },
   "model":  ,// ...all properties of 'model'
   "context": , // ...all properties of 'context'
   "configuration": ,// ...all properties of 'configuration'
}
```

- [ ] Write test for the new endpoints
