### ISSUE TITLE
[TASK]: Run GoLLM on Document fetch

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2677]
**Describe the task**
It will be a better UX if the GoLLM _model-card_ was extracted either on Document upload, or if it doesn't exist already on the `Document` asset, to request it asynchonously.

**Task Items**
- [ ] Update the `Document` asset with a `model-card`, that can receive a GoLLM or MIT card
- [ ] Update the create a Document or fetch a Document to do that work asynchronously
- [ ] Remove fetching GoLLM model-card from the front-end.
