### ISSUE TITLE
[TASK]: Fix the model extraction UX

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2884]
**Describe the task**
How we extract information from TA1 for models needs to be improved.

**Task Items**
- [ ] Add back the `service` dropdown, but put TA1/TA4 instead, with TA1 being the default
- [ ] Change the label from `service` to `Enrichment`
- [ ] Allow user to select one or both services
- [ ] When the user click on `run` do also run the SKEMA variable and align extractions
- [ ] Display in the preview for the model a toggle to allow the user to display either TA1 or TA4 model_card
- [ ] Remove the Provenance action button from the model asset preview (only when in an operator)
