### ISSUE TITLE
export/import/copy project and assets

### ISSUE THREAD

**Issue by bigglesandginger** [DARPA-ASKEM/terarium#2943]
### Need

- Export a project and all related assets (including S3 and ElasticSearch documents) to a file for import
- Import an exported project and all related assets
- Copy a "Template Project"

### Assumptions

- All UUIDs are truly unique.
- All assets, except Workflows, Models, Documents, are atomic/static and thus do not need (nor is it desired) to be duplicated.  
- New UUIDs are only needed to be generated for the actual Project, and Workflows, all other assets will use their assigned UUIDs (thus eliminating unnecessary duplication)

### Task

Provide `hmi-server` REST calls to export a project to a file, import from a file, copy a project.

Export needs to capture:
- Project row from project table
- ProjectAsset rows from project_asset table for given  project_id
- For each Asset export the related source documents (S3 for Datasets, ES for Models, etc (all ES and S3 data can be treated as a blob)
- Save an archive file

Import needs to:
- Import from an archive file
- Generate a new UUID for the Project
- Generate new UUIDs for all Workflows

Copy a Project need to:
- Encapsulate Export and Import skipping the archive middle man, thus:
  - copy the project table row and insert with new UUID
  - copy project_asset rows pointing at new project_id UUID
    - any Workflow project_assets need a new UUID (copy their ES blob to new UUID)

**There is the initial skeleton of an idea in the `orchestration` project (`/mi6/universal_exports.sh`)**

**Comment by pascaleproulx** [comment]
Copying is more important than import/export for the users. As Charles mentioned, import/export is more of a feature for us juggling two deployments. 

In terms of duplicating assets, I though it was fine to just point to the same object since my belief is that any change to the asset going forward will make a new version of the object anyways (e.g. adding a new model card, etc.). But based on Kevin's comment in Slack, it sounds like we are just updating the same asset when we change the model metadata like the model card?

**Comment by YohannParis** [comment]
> my belief is that any change to the asset going forward will make a new version of the object anyways (e.g. adding a new model card, etc.)

This is not happening, unless for transition partners need. Way to complex for this project scope.

Here a more reasonable task list:

### First pass
- [x] Copy `Model` between same environment projects
- [ ] Download/Upload `Model` asset (how to solve UUID conflicts)
- [x] Copy `Dataset` between same environment projects
- [ ] Download/Upload `Dataset` asset
- [ ] Fork `Project` between same environment is a full duplication of UUID and hard assets. No provenance kept, except the new all asset have `DUPLICATED_FROM`.

### Second pass
- [ ] Import/Export _between_ environment. This conserve UUID and move everything. Work in progress with @bigglesandginger script.
