### ISSUE TITLE
[TASK]: Improve GoLLM exctraction

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2996]
**Describe the task**
We need to make sure that GoLLM is getting the best information available.

**Task Items**
- [x] #3001
- [x] #3036
- [ ] Do the same for RegNet `Edges, Vertices, State variables, Parameters`
- [ ] If a _semantic_ `State variables, Parameters, Observables, Transition,etc...` has a grounding identifiers (curie) let's resolve it and fill the description of semantic if empty/null. A solution would be to save the resolved name/description of a concept in the `grounding` object.   Let's talk to @pascaleproulx if we want to display that grounding.description as a placeholder (subdue text) `"From concept: [description]"` if empty.
```json
                "grounding": {
                    "identifiers": {
                        "ido": "0000621"
                    },
                    "name": string,
                    "description": string,
                }
```
- [ ] On the ModelConfiguration extraction, display only the values returned by GoLLM 

**Goal**
Improve GoLLM extraction with Document, Datasets for Model configuration.
