### ISSUE TITLE
[TASK]: Aligning variable from the model preview

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/terarium#3107]
**Describe the task**
We are able to align variables from the model page and model operator but now we want to align variables from other places where it is not working:

These shouldn't be too bad - the `@model-update` function need to be caught to update and refresh the model in `tera-model-description` with these components:
- model from equations operator 
- model from code operator

```html
<tera-model-description
	:model="selectedModel"
	:feature-config="{
		isPreview: true
	}"
	:is-generating-card="isGeneratingCard"
        @update-model="..."
/>
```

The view for the gollm extractions is a different beast, I would say we need a new component for this as other concepts and gollm extraction have completely different data structures.  This would be on the `tera-model-config` component and will replace the `tera-model-semantic-tables` component that is a placeholder at the moment.

maybe something containing on the initials and parameters tables with a table component that shows all the gollm parameters/initials

```html
<new-component>
   <tera-initials-table />
   <tera-parameters-table />
   <new-table-component />
</new-component>
```
Keep in mind how metadata is stored for initials and parameters on a model which is very hacky but works, everything that isn't apart of an `Initial` or `ModelParameter` definition is stored here and we have to map it on the front end:

```
metadata : {
    ...
    initials :{
      ...
    }
   parameters: {
      ...
   }
}
```
**Task Items**
- [ ] update and refresh model when aligning other concepts in `tera-model-from-code` and `tera-model-from-equations-drilldown`
- [ ] add gollm view component
- [ ] add gollm table component with concepts
- [ ] assign varaibles from gollm table component to params and initials

**Comment by YohannParis** [comment]
This is overcede by the new design comming
