### ISSUE TITLE
[TASK]: Clean up populate home screen

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/TERArium#317]
**Describe the task**
Fix up the population of the home screen to correctly use backend to save api calls, add tests, ect

**Task Items**

- [ ]  Write tests for components created
- [x] #393
    *5f6d0e20a58f1dfd52184931 document has 2 entries in xdd?
    *Only 8% (807 of 10,000) have abstracts???
    *Essentially no documents with images found?
- [x] Fix this to reduce API calls: `allProjects.map((project) => ProjectService.getRelatedArticles(project));`
- [ ] Remove hardcoded dataset 'xdd-covid-19' for getRelatedArticles
- [X] Ensure formatting of selected-article-pane's abstract is fine (just removing \<p\> atm)
- [ ] Add images to selected-article-pane
- [X] clean up html from home.vue 
- [X] selected-article-pane.props from array -> single 
- [ ] look into the error handling in getRelatedDocuments to ensure it covers xdd abnormalities 
- [ ] Cache so not to worry about loading time on refresh

**Comment by YohannParis** [comment]
@Tom-Szendrey how are you doing on this task?

**Comment by Tom-Szendrey** [comment]
> @Tom-Szendrey how are you doing on this task? Should we close it, and create new issue that are more precises in scope?

I think we can close this
Cache so not to worry about loading time on refresh -> Load time is no longer an issue it seems now that hmi-server is doing all the lifting. The longest thing is the hot topics results which is still being done via front end

Add images to selected-article-pane -> This is an entire different discussion. Do we want to be searching specifically for results with images? Or for the best results? XDD does not contain many images. Where they do exist we are correctly displaying them

**Comment by YohannParis** [comment]
Okay, let's close this and create new issues when we are re-design the homepage.
