### ISSUE TITLE
[TASK]: Remove copy-pasted world-modelers code

### ISSUE THREAD

**Issue by bencodrington** [DARPA-ASKEM/TERArium#349]
**Describe the task**
When attempting to set up the data-explorer, a lot of code was copied from the existing world-modelers/causemos codebase.

This ticket is to go through and remove the parts we don't need.

**Task Items**
- [x] Verify that the drilldown-panel component is unused and remove it
- [x] Verify that the side-panel component is unused and remove it
- [x] Merge and remove the styles in `hmi-client/src/styles/`. Remove unused styles, move styles that can be scoped to the relevant component, move overrides to `hmi-client/src/assets/css/resets.css`, move global variables and everything else to `css/styles.css`. Use uncharted design tokens wherever possible.
- [x] Remove SASS.
