### ISSUE TITLE
[TASK]: Update Model Configuration

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#3507]
**Describe the task**
How we think and manipulate _model configurations_ does not match how we modelled it in the application. _Model configurations_ are now they own assets that is tied to a specific _model_. A _model_ should not contains values, and a _model configurations_ should not content a _model_.

**Goal**
_Model configurations_ should not be an AMR and instead be a map of properties tied to _symbols_ used in a _model_. 

Here an precise, but not accurate, definition of how a _model configuration_ should be:
```typescript
class SymbolConfig {
    constant: number,
    distribution: object,
    expression: string,
    intervention: object,
    isDummy: boolean,
    source: string,
    type: "initial" | "state" | "parameter", // Depends on the framework, here PetriNet
    value_selected: "constant" | "distribution" | "expression",
}

class ModelConfiguration extends TerariumAsset {
    description: string,
    isCalibrated: boolean,
    model_id: Model["id"],
    values: Map<string, SymbolConfig>,
}
```

**Task Items**
- [ ] Create/update the _model configuration_ asset to represent closely the idea presented above
- [ ] Do a database migration to update all current _model configurations_ in the DB. ask @pascaleproulx if necessary
- [ ] Update `hmi-client` to use the representation
- [ ] Update upload of _model_ JSON files to strip the values of an AMR and create both a _model_ and it's default _model configuration_

**Comment by YohannParis** [comment]
> `SymbolConfig. value_selected` is not needed, these options are not mutually exclusive

They are not mutually exclusive but we need a way on the front-end to display the one the user selected to see.

> If we want to have longer-term maintenance, we may want to have a base object
>
> ```ts
>baseType {
>  name: string,
>  type: string
>}
>```
>and derive concrete Initial, Parameter, and what not by extending the baseType class.

I see your point, therefore what about 

```ts
class SymbolConfig {
    constant: number, // at least one value field we know always exist, doesn't have to be constant
    isDummy: boolean,
    source: string,
}

class State extends SymbolConfig {
    type: Petrinet.State, // enum of strings
    distribution: object,
    expression: string,
    intervention: object
}

class Initials extends SymboleConfig {...}
class Parameter extends SymboleConfig {...}
```

**Comment by blanchco** [comment]
@dvince2 @mwdchang @dgauldie @YohannParis 
Looking at the design I think this should more or less be the general structure we should go for, let me know what you all think:

```ts
class ModelConfiguration extends TerariumAsset {
	name: string;
	description: string;
	isCalibrated: boolean;
	model_id: Model["id"];
	interventions: Intervention[]; // using the current intervention object we have
	values: Map<string, Semantic>;
}

class Semantic {
	type: 'initial' | 'parameter'; // type of semantic
	name: string; // name of semantic
	description: string; // description of semantic
	source: string; // source of semantic
}

class Initial extends Semantic {
	expression: string; // the expression of the initial value (e.g. S0, x + y)
}

class Parameter extends Semantic {
	value: number;
	distribution: Distribution; // the current distribution object we have
	isDefault: boolean; // I believe only a parameter can have a default value?
}
```

**Comment by YohannParis** [comment]
* `class ModelConfiguration` doesn't need `name and description` as they are in `TerariumAsset`.
* `model_id` needs to be camelCase `modelId`
* `Semantic.type` is not needed if we extend Semantic
* Why `ModelConfiguration.interventions` is not within `Parameter`?
* `Parameter.isDefault` the dummy value?

**Comment by blanchco** [comment]
Here's an update structures:
```ts
class ModelConfiguration extends TerariumAsset {
	isCalibrated: boolean;
	modelId: Model["id"];
	values: Map<string, Semantic>;
}

class Semantic {
	type: 'initial' | 'parameter'; // type of semantic
	name: string; // name of semantic
	description: string; // description of semantic
	source: string; // source of semantic
}

class Initial extends Semantic {
	expression: string; // the expression of the initial value (e.g. S0, x + y)
}

class Parameter extends Semantic {
	value: number;
	distribution: Distribution; // the current distribution object we have
	isDefault: boolean; // a boolean to see if the value is a default (dummy) value
        interventions: Intervention[]; // using the current intervention object we have
}

**Comment by blanchco** [comment]
added a Observable class and added a `type` key, this will allow us to easily identify what semantic is what when iterating through the values map

**Comment by YohannParis** [comment]
Based on new distribution supports

```ts
class Parameter extends Semantic {
        type = SemanticType.Parameter;
        id: 'A';
	value: DistributionBerlouni;
	...
}

class Parameter extends Semantic {
        type = SemanticType.Parameter;
        id: 'B';
	value: DistributionPoisson;
	...
}

class Parameter extends Semantic {
        type = SemanticType.Parameter;
        id: 'C';
	value: Constant;
	...
}
```

**Comment by YohannParis** [comment]
```TypeScript
class ModelConfiguration extends TerariumAsset {
	calibrationRunId: CalibrationRun["id"];
	modelId: Model["id"];
	values: Map<string, Semantic>;
}

enum SemanticType = {
      Initial = 'initial',
      Parameter = 'parameter',
      Observable = 'observable'
}

class Semantic {
	name: string; // name of semantic
	description: string; // description of semantic
	source: string; // source of semantic,
        type: SemanticType // type of semantic
}

class Initial extends Semantic {
        type: SemanticType.Initial;
        target: string;
	expression: string; // the expression of the initial value (e.g. S0, x + y)
        unit: string; // for initials this can be a string
}

class Parameter extends Semantic {
        type: SemanticType.Parameter;
        id: string;
	distribution: Distribution; // the current distribution object we have
	isDefault: boolean; // a boolean to see if the value is a default (dummy) value
        interventions: Intervention[]; // using the current intervention object we have
        unit: ModelUnit; //using current unit object
}

class Observable extends Semantic {
       type = SemanticType.Observable;
       id: string;
       states: string[];
       expression: string;
}
```
