### ISSUE TITLE
[TASK]: integrate xDD implicit search capability for titles and abstracts

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/TERArium#355]
**Describe the task**
xDD provides various query parameters to control how the search for publications is performed. The current implementation utilizes a specific query parameter that must be explicitly set to guide matching against paper title. A newer query parameter named "additional_fields" has been recently introduced to facilitate expanding the search terms to also consider searching titles and abstracts in addition to matching against the document text. This task is all about leveraging the new xDD query parameter and refactor the existing implementation accordingly.

Note that valid values for the new query parameter are: title and abstract
Example of usage "additional_fields=title,abstract"

Another xDD parameter named "match" has been added and should always be enabled. Modify the code to always include this parameter to guide xDD to use frequency-based term search.

**Task Items**
- [x] Modify the backend Proxy/Resource implementations to support the new query parameter and remove the old one
- [x] Apply a similar update to the client-side service code (in the data.ts file)
- [x] Modify the data explorer component to automatically enable the new query parameter and remove the existing UI toggle that was added to search for either titles or document text
- [x] Modify the code to also include the "match=true" query parameter to enhance xDD search

**Goal**
An improved search results and a cleaner data-explorer UI

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here
