### ISSUE TITLE
[TASK]: integrate xDD URL extractions

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/TERArium#357]
**Describe the task**
xDD has recently added the capability to fetch URL extractions through the following query parameter:
"known_entities=url_extractions"
The existing code provides some implementation of "known_entities" that requires explicit user input to fetch specific known entities. This task is all about modifying the existing code to automatically pull URL extractions and format them as part of the articles metadata. They also need to be displayed in the DataExplorer and the Document components. The extracted URL extractions should also be shown as a facet the enumerate the different URL sources, e.g., Google, Github, etc. 

**Task Items**
- [x] Modify code to leverage a new type of known entities, namely url_extractions
- [x] Integrate Extracted URLs into the relevant views such as the articles-listview and the Document components
- [ ] create a facet from the URL extractions data and enable filtering papers accordingly

**Goal**
User should be able to automatically see URL extractions and filter papers search results to those that have a given type of (URL) extractions.

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here
