### ISSUE TITLE
[TASK]: Refactor data explorer related code and components 

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/terarium#364]
**Describe the task**
The initial implementation of the Data Explorer includes multiple components that are very similar and can be refactored by removing duplicate code and cleaning things up. For example, the models-listview and the datasets-listview components are almost identical and can be refactored as one component that gets customized with slots through the parent component.

**Task Items**
- [ ] Refactor both the models-listview and the datasets-listview components
- [ ] Refactor duplicate functions especially those implemented at component level to be utility functions. Specifically, "isDataItemSelected" and "toggleDataItemSelected"
- [ ] Remove ResourceType.ALL since there won’t be a single data explorer view that combines the different artifact search results in a single list
- [ ] Refactor facet-specific components such as CategoricalFacet by converting its code into typescript and also by integrating the latest facets version
- [ ] Remove remaining dependency on sass/scss by refactoring relevant components
- [ ] Some functions that manage project assets from the explorer are duplicated and implemented in wrong locations. For example, addResourcesToProject , should be a data service function and ideally its implementation should be done to the backend
- [ ] Functions such as formatDescription should be refactored as utility functions
- [ ] Simplify components such as side-panel-nav by removing unused and likely unneeded props such as isGreyscale 
- [ ] The Pagination component (simple-pagination) has been commented out in the data explorer. Either remove the code and the component if pagination is not needed, or fix the component and use it. The same can be said about the AutoComplete component

**Goal**
A clear and concise description of what the end result must have for it to be approved as complete.

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here
