### ISSUE TITLE
[TASK]: Improve management of project assets at the HMI client side

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/terarium#367]
**Describe the task**
Currently, project assets are fetched from the backend and tracked at the client side in different ways. For example, a global pinia store tracks activeProject and activeProjectAssets knowing that activeProject in itself includes a field called assets. Furthermore, functions that enable working with project assets such as addResourcesToProject need to be refactored.

On a related note:
Fetching projects returns a list that includes an "assets" field. But this field is limited in its representation as an array of numbers and thus a separate call to retrieve the assets metadata has to be done via `/project/{id}/assets`. Unfortunately, this means assets are now available in two ways and one of them is limited in its representation/structure. To avoid confusion, the HMI server should explicitly omit returning the "assets" field from the project metadata. Subsequently, the types: `ProjectAssets` and `SimpleProjectAssets`  should be revisited and refactored

On another related note:
Review concept facet types which currently seem identical to project asset types? (i.e., `ConceptFacetsType` and `ProjectAssets` 

**Task Items**
- [ ] Refactor functions that fetch and update project assets as service functions
- [ ] Refactor how project assets are tracked and made available to the various code components
- [ ] Refactor ProjectAssets and SimpleProjectAssets and remove the "assets" filed from project metadata
- [ ] Review concept facet types which currently seem identical to project asset types? (i.e., ConceptFacetsType and ProjectAssets 
- [ ] Handle cases where assets to be added already exist or when deleting an asset that has been already removed

**Goal**
A clear and concise description of what the end result must have for it to be approved as complete.

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here
