### ISSUE TITLE
[TASK]: clean up the `--gap` variables

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#3670]
**Describe the task**
We have an incomplete list of gap, margin, and padding variables and not all applied.
Their is a lack of consistency in the CSS and it's a mess.

**Task Items**
- [x] Find all the potential values used in the application `.25rem, .5rem, .75rem, etc`
- [x] Check if Tailwind already offers those values
- [ ] Update the [CSS variables](https://github.com/DARPA-ASKEM/terarium/blob/49ca5a9e0720639b5a1bf7d4e274c3d52efd7bc6/packages/client/hmi-client/src/assets/css/theme/_variables.scss#L866) to a up to date list of gaps, from XXS to XXL maybe

**Goal**
This needs to be done in a one swoop and the merge commit id should be added to the ignore list.
https://github.com/DARPA-ASKEM/terarium/blob/main/.github/CONTRIBUTING.md#ignore-commits-in-the-blame-view
