### ISSUE TITLE
[TASK]: Refactor how xDD highlights/snippets are fetched and displayed

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/TERArium#368]
**Describe the task**
The data explorer fetch articles from xDD including snippets (i.e. highlights) whenever search term(s) are provided. Snippets are calculated at the xDD side with formatting/styling that emphasize the search term(s) differently. The emphasized styling applied by xDD is then augmented on at the HMI client side by making each search term in the provided snippets "bold". This client side augmentation is less optimal because it performs exact term comparison and thus lacks formatting similar terms. Furthermore, performing such augmentation at the client side adds performance overhead. Ideally, we need to communicate with xDD team and ask them to properly format target word(s) in the included highlights in a way that is consistent with the styles applied in the Data Explorer. 

For example, searching for "vaccination" would highlight all matching concepts in the data explorer with yellow background. xDD paper highlights that includes the exact word "vaccination" will be shown in bold which is inconsistent with the yellow background for matching concepts. Also, because exact word comparison is applied, all similar words such as "vaccine" or "vaccinated" will NOT be styled properly. This task is all about re-visiting how xDD highlights are styled ideally at the xDD side while ensuring consistent styling with other search matches.

**Task Items**
- [ ] remove highlight styling at the client side
- [ ] Communicate with xDD team and ensures proper styling applied to the incoming search result highlights
- [ ] Ensure consistent styling in the data explorer between xDD search and other HMI search such as concept search

**Goal**
A clear and concise description of what the end result must have for it to be approved as complete.

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here

**Comment by dvince2** [comment]
This task looks to have been done at some point in the last ~2 months.  xDD is returning search terms tagged with the `hl` class which allows us to style however we want without needed to search.
