### ISSUE TITLE
[TASK]: Remove `skema-text-reading`

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#3688]
**Describe the task**
Needs to remove `skema-text-reading` from the application.
Please create a PR for each of the following tasks.

**Tasks**
- [x] Remove `skema-text-reading` from the `hmi-client` UI (align, and exctraction button)
- [x] Remove `skema-text-reading` from the `hmi-client` services
- [x] Remove `skema-text-reading` from the `hmi-server` extraction service 
- [x] Remove `skema-text-reading` from the `hmi-server` controllers
- [x] Remove `skema-text-reading` from the `hmi-server` proxies
- [x] Remove `skema-text-reading` from the `hmi-server` configuration
- [x] Remove `skema-text-reading` from the `orchestration`
- [x] Update dev environment
- [x] Update staging environment
- [ ] Update prod environment
