### ISSUE TITLE
[TASK]: Fix count of xDD articles displayed in Explorer and refine pagination

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/terarium#369]
**Describe the task**
xDD supports some form of Pagination for fetching large amounts of results. Early data explorer implementation provided a toggle that controls whether xDD pagination should be enabled or not through the query param "full_results". However, it was noted that when xDD pagination is enabled the search results are not sorted by relevancy and thus the feature is currently disabled in the data explorer. Ideally, we should reach out to the xDD team to clarify the pagination feature while still fetching ranked results. Nonetheless, with the pagination disabled only a max number of articles is set (currently to 100) and no pagination is provided. This can be confusing since the user can see that a maximum 100 article exist but the facets aggregations reflect much larger size of results. The fix should refactor the label that displays the results count to say something like: "showing 100 articles out of total x results" wherein x is the number of hits provided by xDD. This refactoring work may result in completely removing the unused simple-pagination component.

**Task Items**
- [x] refactor the displayed count of search results
- [ ] communicate with xDD team re proper pagination or to retrieve the true number of hits even if the results only returns a fixed number of matching papers
- [ ] remove the unused simple-pagination component

**Goal**
A clear and concise description of what the end result must have for it to be approved as complete.

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here

**Comment by dvince2** [comment]
From Ian: I also added a `hits` count on the articles route

**Comment by dvince2** [comment]
For now, we've added the "X of Y documents" option. xDD has been made aware of the sorting issue and are working to resolve it.
