### ISSUE TITLE
[TASK]: Optimize fetching raw CSV data as a preview for a selected dataset

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/Terarium#372]
**Describe the task**
Opening a dataset from the side panel results in fetching its raw CSV data which can be significant if the size of the dataset is large. We should either returns a preview (e.g., the first 50 rows) or implement caching. Similarly, fetching document extractions such as tables and figures can be heavy.

**Task Items**
- [ ] Fetch only subset of the dataset for preview
- [ ] Apply the same optimization for document extractions such as tables and figures
- [ ] Expose a toggle in the UI and the data service query parameter to reflect and control whether the preview is shown in wide format or not

**Goal**
A clear and concise description of what the end result must have for it to be approved as complete.

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here
