### ISSUE TITLE
[TASK]: Refactor and Move Facets Implementation to HMI server

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/Terarium#373]
**Describe the task**
Facets for models and datasets are currently constructed on the client side. Also, applying facet filters is done at the client side. This is very inefficient because ideally applying a facet filter should result in an API call that recalculates both the data and the facets aggregation in a way similar to what is currently done with XDD articles. 

For models and datasets, concept facets are served through a separate endpoint that makes the integration at the client side harder because fetching models, for example, is not aware of any concept filters applied. The currently implemented workaround utilizes concepts-facet filtering by filtering the list of models, identifying related curies and pass them as query parameter filters to the concepts facet API, which is less optimal. This is due to the fact that the endpoint for fetching concept facets does NOT receive filter parameters. So it is not possible to tell the concepts facets API to only provide concepts for models matching a given search term or criteria.

On a similar note, the client side filtering of models/datasets against search terms (by manaully searching the name and description fields) as well as against concept names. The endpoints for fetching models and datasets need to take parameters such as search-terms and concepts in order to facilitate such filtering and all such logic should be moved into a dedicated service module within the HMI server that hides all the search details and provide a thin interface for the client consumption

NOTE this require changes to the data service and alignment on how concept facets shall be provided.

**Task Items**
- [ ] Move the computation of facets data/aggregation for models and datasets to the HMI server (see for example the comment that says "simulate applying filters to the model query" at data.ts)
- [ ] Move logic that filter models and datasets via search criteria to the HMI server, e..g, applyFacetFiltersToModels
- [ ] Consolidate concept facets as part of the models/datasets search results response similar to how xDD provides it

**Comment by YohannParis** [comment]
@dvince2 @Tom-Szendrey could you look at this issue and see how easy it will be to do? Just a guestimate.
