### ISSUE TITLE
Implement intervention policy operator

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#3994]
Implement the new `InterventionPolicy` operator.

![Image](https://github.com/DARPA-ASKEM/terarium/assets/636801/4b546fde-8619-462c-930c-e3d13fe28b0f)

Figma [page](https://www.figma.com/design/EoihrRoNNbuOAJtudKqp7L/Terarium---June-2024?node-id=665-19085&t=W6HvjdQzKwGP3uq3-1) and [prototype](https://www.figma.com/proto/EoihrRoNNbuOAJtudKqp7L/Terarium---June-2024?page-id=665%3A19085&node-id=714-61424&viewport=1397%2C-750%2C0.16&t=sN3S8J6WpKwlSZxF-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=714%3A61424&show-proto-sidebar=1)

**Task to be made as PR**

- [x] Write the `InterventionPolicy` API services
- [x] Create the `InterventionPolicy` workflow node
- [x] Create the `InterventionPolicy` workflow drilldown
- [x] Create the `Intervention` tera-block
- [x] Add the `InterventionPolicy` sidebar
- [ ] Add the `InterventionPolicy` output preview panel with charts

**Comment by YohannParis** [comment]
@asylves1 when ready to start, let's have a meeting with @ngraham76 to go through all the steps.
