### ISSUE TITLE
[TASK]: Validate Configuration operator update

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4111]
**Describe the task**

This is a sketch of the UI for the Validate Configuration operator powered by Funman.

**Task Items**
- [ ] Need UI/UX designer review and Figma version of this
- [ ] Need confirmation from Daniel Bryce on whether _observables_ can be variables in state constraints
- [ ] Need example Funman request for differential constraints
- [ ] This function generates state constraints from a given time-series dataset, should be used/implemented in Terarium [url](https://github.com/DARPA-ASKEM/experiments/blob/5b6c331ab0dec90180cb353472f23e346ab2ca89/funman/notebooks/timeseries_constraints.py#L253). The number of boxes can probably be set as `~1.0 / tolerance` from Funman settings.

**Screenshots**
![Validate Model sketch](https://github.com/user-attachments/assets/f11e5e31-7b9c-4c8c-b634-09e2b3cde019)
