### ISSUE TITLE
[FEAT]: Operator node output menu

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4268]
### Description

* Display a `+` button when hovering a node output
* When the button is clicked, open a contextual menu to connect operator that offers to connect new operators that accept that output type as input
* Add the new operator already linked to the output

### Design

![image](https://github.com/user-attachments/assets/11b1b25d-da34-4409-9449-2bc0480596ea)

* Figma source for the full version which includes AI assistant to be done in anothe PR: https://www.figma.com/design/mAGUkTBlT0Yu4L5iGSEcb3/Terarium---Master?node-id=1-45283&t=jtTCGImGpomKDWYx-1

``` [tasklist]
### task
- [ ] Enable menu on hover
- [ ] Create list of possible outputs to inputs
- [ ] Enable node creation from menu
- [ ] Create edge from outputs to inputs
```
