### ISSUE TITLE
[TASK]: Fix REST subobject pattern

### ISSUE THREAD

**Issue by dvince2** [DARPA-ASKEM/TERArium#434]
**Describe the task**
Align our API paths to those found in data-service

**Task Items**
- [x] /models/descriptions/{id} -> /models/{id}/descriptions  
- [x] /models/parameters/{id} -> /models/{id}/parameters  
- [x] /simulations/runs/descriptions/{id} -> /simulations/runs/{id}/descriptions  
- [x] /simulations/runs/parameters/{id} -> /simulations/runs/{id}/parameters

**Goal**
N/A

**Screenshots**
N/A

**Additional context**
[PR to changes on data-service](https://github.com/DARPA-ASKEM/data-service/pull/140)
