### ISSUE TITLE
[TASK]: Setup Users managements service (based on keycloack users)

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/Terarium#44]
**Describe the task**
* Using the _PostGres_ database, add a service to manage TERArium users.

**Task Items**
- [ ] Create a table within _PostGres_ database
- [ ] Set a _User Management_ service in _Quarkus_ (HMI backend)
- [ ] Interface with _Keycloack_ service as the source for new/existing users
- [ ] Add the ability to create groups of users, with one person being _administrator_ of the group

**Goal**
* A good way to test if this is complete is with a series of _end to end_ tests:
- [ ] When a user is created with _Keycloack_, is it able to create projects
- [ ] When a user is deleted, offers a process to transfers theirs projects to the _administrator_ of their group, or to delete them

**Comment by YohannParis** [comment]
Is this still relevant with the bunch of tasks that @bigglesandginger is working on?

**Comment by dgauldie** [comment]
this is a duplicate
