### ISSUE TITLE
[TASK]: improve `tera-toggleable-edit`

### ISSUE THREAD

**Issue by shawnyama** [DARPA-ASKEM/terarium#4416]
**Describe the task**
Improve `tera-toggleable-edit`

**Task Items**
- [x] click the entire text to start editing
- [x] put a keypress="enter" listener on the input, so you don't have to click the tiny checkbox if you want to keep your hands on the keyboard
- [x] "Escape" to cancel
