### ISSUE TITLE
[TASK]: Simplify and secure access to assets

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4440]
**Describe the task**
As of know we are sending a `projectId` every time we are using an asset endpoint. This is too check if the user has the right to the asset. Unfortunately this allow to enter a `projectId` to which the user as enough rights to access any assets.

The goal is to, instead, check if a user as access to an asset by checking its relationship with projects, and check if the user as authorization on any of those.

This new task cancel #4228 as now we need to make a difference between assets saved by the user to a project with the `isTemporary` flag. 

@dgauldie @dvince2 @mwdchang please advise if this is a good course of action.

**Task to be done in different PRs**
- [ ] Update the controller that creates assets to allow a `projectId` to be associated with.
- [ ] Update the front-end to provide the `projectId` on ALL asset creation call.
- [ ] Update the controllers to _require_ `projectId` on ALL asset creation endpoints.
- [ ] Update authorization methods for assets to find an asset related `projectId` to fetch authorization.
- [ ] Leverage the new cache to improve performances on `user <-> projectId` relationship.

**Comment by bigglesandginger** [comment]
FrameworkController - has no permission checks
Many controllers do not has permission checks on all functions... should we not add them?

**Comment by dvince2** [comment]
Outstanding tasks:

- [ ] Convert ModelConfiuration to be a ProjectAsset (currently overrides getProjectIdForAsset() to fetch the associated modelId to look up with, however, I am imagining that if one adds a ModelConfiguration and does not link a Model to it, it will throw errors.
- [ ] Convert Simulation to be a ProjectAsset
- [ ] Convert other Workflow things that are stored in the DB to be ProjectAssets - reason being that there is a function getProjectIdForAsset() that looks up the projectId from the project-asset table.
- [ ] TODO: Upload datasets from GitHub
- [ ] TODO: Usages of ProjectController.createAsset() - I am imaging that this function disappears entirely.
- [ ] These are the things I know of.
- [ ] Currently I am able to Upload a dataset, model, code, and create a new workflow, model, and code; add a model to a workflow and create a ModelConfiguration and InterventionPolicy.
- [ ] When/If ModelConfiguration becomes a ProjectAsset, the saveAs() function in save-asset.ts would need correcting (and the tempgap I did for name and id could be erased.

**Comment by dvince2** [comment]
The scope on this issue is growing large, and doesn't actually get us anything in the end. closing.
