### ISSUE TITLE
[TASK]: Move searchbar functionality from data explorer into Navbar; Make Data explorer its own view

### ISSUE THREAD

**Issue by echl** [DARPA-ASKEM/TERArium#457]
**Describe the task**
Instead of having the data explorer be opened with the current button, make it its own view that is navigated to when user makes a search from the navbar.

**Task Items**
- [ ] Move data explorer into its own view
- [ ] Move functionality of data explorer search into navbar search
- [ ] Remove searchbar from data explorer view
