### ISSUE TITLE
[TASK]: UX - Home page projects table - stats column

### ISSUE THREAD

**Issue by ngraham76** [DARPA-ASKEM/terarium#4675]
**Describe the task**
The projects **table** stats needs a few things added.

**Task Items**
- [ ] Tool tips on each stat item, just like we see in the project cards
- [ ] When there are no resources or workflows in a project, a "0" should be displayed
- [ ] 'Workflows' stat needs to be added to the table stats

**Screenshots**
![image](https://github.com/user-attachments/assets/3dfeb220-35da-4865-a6e6-e4f7e8728fa4)
![image](https://github.com/user-attachments/assets/8f93d170-d18b-41c1-b180-9868bfe5cd84)
