### ISSUE TITLE
[TASK]: setup slack-channel/GitHub notifications for CI

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/TERArium#50]
**Describe the task**
GitHub build tasks should notify the team if a build fails for a repo. A slack channel should be setup to highlight issues for the team to fix.

**Task Items**
- [ ] setup askem-notify channel
- [ ] link repo build errors to notify channel
- [ ] each error should describe what the error is and what repo the error occured in

**Goal**
All github builds should notify the team if there are errors

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here
