### ISSUE TITLE
[TASK]: work with CloudOps for Kube support

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#51]
**Describe the task**
Work with cloud ops team to implement kubernetes scripts to deploy terarium in AWS staging and PROD environments and our local dev environments.

**Task Items**
- [ ] Terarium is deployed on staging environment
- [ ] Terarium is deployed on production environment
- [ ] Terarium can be deployed on local dev environment

**Goal**
Simple scripts for devs and cloud ops to deploy the latest versions of terarium onto various deployments

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here

**Comment by YohannParis** [comment]
Is this done?
