### ISSUE TITLE
[TASK]: Refinements to the modal comparing the values of a parameters across configurations

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#5470]
**Describe the task**
Refinements to the modal comparing the values of a parameters across configurations. 

- [ ] Add the parameter description below the modal title
- [ ] Fix the range visualization (see design in mockup below)

**Task Items**
- [ ] list of items for completion
- [ ] another item

**Goal**
A clear and concise description of what the end result must have for it to be approved as complete.

**Screenshots**
We can see the parameter description on the config page.
![Image](https://github.com/user-attachments/assets/cfd6e870-4ccf-4ff2-b45e-1de89a64f137)

It would be useful to also see it in the modal when comparing values from all configurations for that particular parameter. Also note that the viz to show the range of values is not working.
![Image](https://github.com/user-attachments/assets/e647f259-395a-4ad9-850c-5ceb5663e59b)

**Comment by jamiewaese-uncharted** [comment]
Here is what it's supposed to look like:
![Image](https://github.com/user-attachments/assets/f335d265-f219-4984-b474-77aee2cd834f)

Note:
- New subtitle under the header: This is the variable or parameter description.
