### ISSUE TITLE
[TASK]: Remove SASS

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/TERArium#58]
**Describe the task**
A clear and concise description of what the task is.

**Task Items**
- [ ] list of items for completion
- [ ] another item

**Goal**
A clear and concise description of what the end result must have for it to be approved as complete.

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here

SASS was added as a dependencies to port the `data-explorer` #27

- [ ] Remove SASS on all components
- [ ] Remove the dependencies

**Comment by amostafa-uncharted** [comment]
This work should be done after merging this PR: https://github.com/DARPA-ASKEM/TERArium/pull/133 because it may have some other SASS dependencies
