### ISSUE TITLE
Tweaks to calibrate ensemble charts settings

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#5819]
**Describe the task**
We reviewed calibrate ensemble with Sabina and here are some tweaks based on her feedback:

**Task Items**
- [x] Move `show individual models` checkbox at the top of the Ensemble variables over time section
- [x] Have 'Show individual models` selected by default
- [x] Display error plots for mapped variables to data by default
- [x] Display model weights charts by default
- [x] On the thumbnail of calibrate ensemble, we should show the ensemble model variables over time that were mapped to data by default, similar to the Calibrate operator

**Screenshots**
![Image](https://github.com/user-attachments/assets/9bc9e08e-9969-4a0a-98cc-4177df94dbc2)
