### ISSUE TITLE
[TASK]: Improve search bar user experience

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/TERArium#630]
**Describe the task**
The search bar got new features, suggestions and autocompletion, but the whole user experience is poor.

**Task Items**
- [x] Use [PrimeVue autocomplete component](https://primevue.org/autocomplete)
- [x] Integrate using @jamiewaese-uncharted [Figma design](https://www.figma.com/file/lOoGAsDwLfMmP3u5qzKHRh/TERArium-HMI-Designs---PrimeVue-version?node-id=8563%3A55610&t=GXxs6bMfVOgAf4Ll-4)
- [x] Able to select a suggestion via keyboard's arrow keys
- [x] Do not block the input typing after 3 characters
- [x] Execute a search when suggestions or autocomplete has been selected
- [x] #633
- [x] Auto complete should hide when there are no suggestions (start to type `github`.  At `gith` there are suggestions, and `githu` has no suggestion but bar remains)

**Goal**
Improve those features to feel more like a _Google_ search bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/636801/216382597-3cde9a49-7e02-4df8-b5b6-b2564f9005b9.png)

**Comment by echl** [comment]
@YohannParis 

"Do not block the input typing after 3 characters" This was broken after recent merge, will fix in an upcoming PR.

**Comment by YohannParis** [comment]
> "Use [PrimeVue autocomplete component](https://primevue.org/autocomplete)"
> 
> * I looked into using this component and I don't think it's worth it to use it. Less flexibility than InputText and Menu combo and requires refactoring that won't necessarily give any benefit.

We should leverage prime component as much as possible and to implement @jamiewaese-uncharted design.
<img width="865" alt="Screen Shot 2023-02-02 at 12 06 25" src="https://user-images.githubusercontent.com/636801/216393128-7eab5381-a64c-4d44-87dc-092c21d6dfb9.png">


> " Able to select a suggestion via keyboard's arrow keys"
> 
> * This is already partially implemented. Using the arrow keys highlights different selections on the dropdown menu, and hitting enter will search but due to styling changes they highlight colour is the same as the regular unhighlighted colour, it seems.

This does not work for me on Chrome on _Staging_ nor _Production_.

**Comment by echl** [comment]
> > "Use [PrimeVue autocomplete component](https://primevue.org/autocomplete)"
> > 
> > * I looked into using this component and I don't think it's worth it to use it. Less flexibility than InputText and Menu combo and requires refactoring that won't necessarily give any benefit.
> 
> We should leverage prime component as much as possible and to implement @jamiewaese-uncharted design. <img alt="Screen Shot 2023-02-02 at 12 06 25" width="865" src="https://user-images.githubusercontent.com/636801/216393128-7eab5381-a64c-4d44-87dc-092c21d6dfb9.png">
> 

Of course I may be wrong but I don't see the advantage that the Autocomplete component has in implementing jamie's designs. 

> > " Able to select a suggestion via keyboard's arrow keys"
> > 
> > * This is already partially implemented. Using the arrow keys highlights different selections on the dropdown menu, and hitting enter will search but due to styling changes they highlight colour is the same as the regular unhighlighted colour, it seems.
> 
> This does not work for me on Chrome on _Staging_ nor _Production_.

It tried it on chrome on staging now: 

https://user-images.githubusercontent.com/16358728/216395716-46c23419-d86d-4ccc-9087-8803e4a0f715.mov

What's missing is just the highlighting (which already comes with the menu component, I think the global styling changes got rid of it) and making the highlighted text appear automatically appear in the searchbar (dunno if this is a requirement, but this is what google's searchbar does. Fyi the autocomplete component doesn't do this either)

Anyway I'm just making these points from the perspective of making our lives easier, saving time, and not doing redundant work.

**Comment by YohannParis** [comment]
@shawnyama could you add a video of the new autocomplete?

**Comment by shawnyama** [comment]
> @shawnyama could you add a video of the new autocomplete?
[
](https://user-images.githubusercontent.com/28237258/217295223-441bf10e-9ee2-4389-9517-2d6fb37ab975.mov)
