### ISSUE TITLE
[TASK]: 

### ISSUE THREAD

**Issue by tangopapatime** [DARPA-ASKEM/TERArium#668]
**Describe the task**
Change the **hmi-client** `console.log` to use the new logging rest end point so that logs can be sent to the **hmi-server** for log extraction on prod and staging.

**Task Items**
- [ ] change all console logs to use rest end
- [ ] enable local logging from a dev environment
- [ ] add linting rule using `console.log`

**Goal**
Client logs are now sent back to the `hmi-server` for collection every 5 seconds.

**Screenshots**
N/A

**Additional context**
Eventually these logs will be used to track user actions and activity.
