### ISSUE TITLE
[TASK]: Refactor document related code and services

### ISSUE THREAD

**Issue by dvince2** [DARPA-ASKEM/TERArium#678]
**Describe the task**
Clean up and refactor document related code in the server and front end

**Task Items**
- [x] remove references to xDD, paper, article, etc in the front end and replace with Document
- [ ] remove references to xDD in the back end and replace with Document
- [ ] update api paths between hmi server and client to not have xDD in the path. 
- [ ] refactor document service into the hmi server
- [ ] update orchestration project to have document service removed

**Goal**
Remove ambiguity and settle on use of "Document".  Remove application complexity by getting rid of extra document-service proxy layer

**Additional context**
@Tom-Szendrey will be tackling the front end refactoring
@dvince2 will be refactoring back end, removing document service and changing API path
