### ISSUE TITLE
[TASK]: Integrate DOI checker to display PDF of Document

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#728]
**Describe the task**

> Integrate DOI checker that shows some of the shareable-ness of a given paper's DOI https://www.howcanishareit.com/ (or ask XDD to use it to produce a flag that the PDF is available). For those papers, once it is saved to the project, upload the pdf automatically to show when user toggle from extracted content to PDF as in this design. — @pascaleproulx 

**Task Items**
- [ ] Talk to @iross (xDD) about the feasibilty of adding that flag on their end. If not create one
- [ ] Provide the toggle button on the _Document_ view to switch between HTML and PDF
- [ ] Create the views to display PDFs
- [ ] Talk to @fivegrant (Jataware) about `data-service` saving the PDF in S3, linked to the object

**Screenshots**

![image](https://user-images.githubusercontent.com/636801/219394711-2942d93f-5259-41e6-a26f-17a36dccd09e.png)
![image (1)](https://user-images.githubusercontent.com/636801/219394707-f5b9be5a-3dc4-41cf-a64a-6b9f9e3049af.png)

**Comment by pascaleproulx** [comment]
old
